### ISSUE TITLE
chmod: cannot access '/androidfs/acestream.engine/python/bin/python': No such file or directory

### ISSUE THREAD

**Issue by armen181** [sybdata/acearm#1]
acestream.engine/androidfs/system/lib/libbacktrace.so
acestream.engine/androidfs/system/lib/libutils.so
acestream.engine/androidfs/system/lib/libcrypto.so
acestream.engine/androidfs/system/lib/libpcre.so
acestream.engine/androidfs/system/lib/liblog.so
acestream.engine/androidfs/system/lib/libGLESv2.so
acestream.engine/androidfs/system/bin/
acestream.engine/androidfs/system/bin/acestream.sh
acestream.engine/androidfs/system/bin/linker
acestream.engine/androidfs/system/bin/busybox
acestream.engine/androidfs/system/etc/
acestream.engine/androidfs/system/usr/
acestream.engine/androidfs/system/usr/share/
acestream.engine/androidfs/system/usr/share/zoneinfo/
acestream.engine/androidfs/system/usr/share/zoneinfo/tzdata
acestream.engine/androidfs/storage/
acestream.engine/acestream.start
acestream.engine/acestream.stop
Removing intermediate container 5fa38361690a
 ---> 0e210c69dee1
Step 3/6 : RUN mv /tmp/acestream.engine/ /
 ---> Running in a838d09312b4
Removing intermediate container a838d09312b4
 ---> 0fc974822ae8
Step 4/6 : RUN find /acestream.engine/androidfs/system -type d -exec chmod 755 {
} \;&& find /acestream.engine/androidfs/system -type f -exec chmod 644 {
} \; && chmod 755 /acestream.engine/androidfs/system/bin/* /androidfs/acestream.engine/python/bin/python
&& rm -rf /tmp/*     && cd / && git clone https://github.com/pepsik-kiev/HTTPAceProxy.git && mkdir -p /mnt/films/
 ---> Running in ec9108e724f8
chmod: cannot access '/androidfs/acestream.engine/python/bin/python': No such file or directory
The command '/bin/sh -c find /acestream.engine/androidfs/system -type d -exec chmod 755 {
} \; && find /acestream.engine/androidfs/system -type f -exec chmod 644 {
} \; && chmod 755 /acestream.engine/androidfs/system/bin/* /androidfs/acestream.engine/python/bin/python 
&& rm -rf /tmp/* && cd / && git clone https://github.com/pepsik-kiev/HTTPAceProxy.git && mkdir -p /mnt/films/' 

returned a non-zero code: 1

**Comment by sybdata** [comment]
Fix: `chmod 755 /acestrem.engine/androidfs/system/bin/* /acestrem.engine/androidfs/acestream.engine/python/bin/python`

[https://paste.ee/p/UqETv](url)

[https://github.com/sybdata/acearm/blob/master/Dockerfile](url)
